sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6

before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

install:
    - composer install --no-dev --no-scripts --quiet --optimize-autoloader

script:
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,web/app/plugins/,vendor/ -n -s .
