sudo: false
language: php
php:
  - 7.1
  - 7.0

before_install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master

install: composer install --no-dev --no-scripts --quiet --optimize-autoloader

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
