sudo: false
language: php
php:
  - 7.1
  - 7.0

before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

install: composer install --no-dev --no-scripts --quiet --optimize-autoloader

before_script: composer require atoum/atoum

script: vendor/bin/atoum
